library(tidyverse)
library(ARTool)
library(lme4)
library(lmerTest)
library(ggplot2)
library(qqplotr)
library(emmeans)
library(dplyr)
library(lme4)
library(stargazer)
library(car)
library(emmeans)
library(tidyr)
library(psych) # for describeBy
library(ggbeeswarm)
library(FSA)
# Statistical analysis for the CBA-age project.
# This script reads in the csv files generated by the ephys analysis program
# when the figures are plotted from datatables.
# The CSV files have a LOT of different variables, so we select the
# "best Rs" measured values,


do_stats <- function(csvfile, variable, ymin, ymax, analysis_date) {
    d <- read.csv(csvfile)
    cat(sprintf("\n\n\n*********************************************\n"))
    print(sprintf("Var to test: %s from %s", variable, csvfile))
    testvars <- c(variable, "Subject", "age_category", "sex")
    d2 <- d[, testvars]
    d2 <- drop_na(d2, variable) # remove empty rows.
    d2$sex <- factor(d2$sex)
    d2variable <- as.numeric(d2$variable) # make sure this is a number

    d2$Subject <- factor(d2$Subject)
    d2$age_category <- factor(d2$age_category, levels = c("Preweaning", "Pubescent", "Young Adult", "Mature Adult", "Old Adult", "unknown"))
    # generate a qqplot and write to disk
    # datestr <- format(Sys.time(), "%Y.%m.%d %X") # data of analysis/plotting
    qqfile <- sprintf("R_statistics_plots/%s_age_qq_%s.pdf", variable, analysis_date) # name of the qq plot file

    datestr <- format(Sys.time(), "%Y.%m.%d %X") # data of analysis/plotting
 
    qqp <- ggplot(d2, aes_string(sample = variable, color = "age_category"), ) +
        geom_qq_band(bandType = "pointwise", mapping = aes(fill = "Normal", color = "age_category"), alpha = 0.5) +
        stat_qq_point() +
        stat_qq_line(linewidth = 0.5) +
        scale_fill_discrete(name = "Distribution") +
        facet_wrap(~sex) +
        labs(title = sprintf("%s by age", variable)) +
        theme(plot.title = element_text(hjust = 0.5, size = 12, face = "bold")) +
        labs(tag = sprintf("%s %s", qqfile, datestr)) +
        theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
        theme(plot.tag.position = c(0.95, 0.01)) +
        theme(plot.tag = element_text(size = 6, hjust = 1))

    ggsave(file = qqfile, plot = qqp, width = 6, height = 4)
    cat(sprintf("saved qq plot: %s\n", qqfile))

    # linear regression on the data as a function of age.
    # lmfile <- sprintf("R_statistics_plots/%s_age_regression_%s.pdf", variable, analysis_date) # name of the qq plot file
  
    # lm_model = lm(d2[, variable] ~ age_category, data = d2) 
    # # print(summary(lm_model))
    # stargazer(lm_model, header=FALSE, type='text')
    # par(mfrow= c(2,2))
    # par_fitted <- tibble(d2$age_category, )
    # # lmplot <- plot(lm_model)
    # lmplot <- ggplot(d2, aes_string(x = "age_category", y = variable)) +
    #     geom_point() +
    #     geom_smooth(method = "lm", color="red", fill="#0088ff", se = TRUE) +
    #     labs(title = sprintf("%s by age", variable)) +
    #     theme(plot.title = element_text(hjust = 0.5, size = 12, face = "bold")) +
    #     labs(tag = sprintf("%s %s", lmfile, datestr)) +
    #     xlim(0, 600) +
    #     ylim(ymin, ymax) +
    #     theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    #     theme(plot.tag.position = c(0.95, 0.01)) +
    #     theme(plot.tag = element_text(size = 6, hjust = 1))
    # ggsave(file = lmfile, plot=lmplot, width=6, height=4)
    # cat(sprintf("saved lm plot: %s\n", lmfile))
    cat("====================================\n")


    graphics.off()
    options(width = 120)
    sa <- describeBy(d2[, variable], d2$age_category)
    print(sa)
    # cat(" \n")
    # cat("*****ANOVA*****\n")
    # # straight 1-way ANOVA (ignore sex)
    # m_anova <- aov(d2[, variable] ~ age_category,
    #     data = d2,
    #     contrasts = list(age_category = "contr.sum")
    # )
    # # cat("\n")
    # # run a linear mixed effects model
    # # m_anova <- lmer(d2[, variable] ~ age_category + (1|Subject),  data = d2)
    # print(summary(m_anova))
    # a_AR <- anova(m_anova)
    # print(a_AR)
    # pvalue = a_AR[["Pr(>F)"]][1]

    # sum_test <- summary(m_anova)
    # sum_test <- unlist(summary(m_anova))
    # # run a post-hoc test
    # # Tests consequetive differences in age.
    # m_anova.emml <- emmeans(m_anova, consec ~ age_category)
    # print(sprintf("      *** Var  %s from %s", variable, csvfile))
    # print(summary(m_anova.emml))

    # if (pvalue < 0.05) {
    #     title <- sprintf("Posthoc pairs for %s\n", variable)
    #     cat(title)
    #     emm <- emmeans(m_anova, ~age_category)
    #     tau_pairs <- pairs(emm, simple = "age_category") # interested in effect of age pm;u
    #     print(summary(tau_pairs))
    # } else {
    #     cat("No significant differences found, no post-test\n")
    # }
    # # generate a boxplot and write to disk
    # plotfile <- sprintf("R_statistics_plots/%s_Age_%s.pdf", variable, analysis_date)
    # cat("====================\n")
    # gp <- ggplot(d2, aes_string(x = "age_category", y = variable, color = "age_category")) +
    #     geom_boxplot(alpha = 1, notch = TRUE) +
    #     theme_bw() +
    #     xlab("Age") +
    #     ylab(variable) +
    #     # geom_point() +
    #     geom_beeswarm(alpha = 0.5, cex = 1, size = 1, dodge.width = 1.5, outlier.size = 1.0, outlier.stroke = 0.5) +
    #     scale_fill_manual(values = rep(NA, 2)) +
    #     scale_color_manual(values = c("pink", "light green", "sky blue", "brown", "grey", "black")) +
    #     ylim(ymin, ymax) +
    #     labs(title = sprintf("%s by Age", variable)) +
    #     theme(plot.title = element_text(hjust = 0.5, size = 12, face = "bold")) +
    #     labs(tag = sprintf("%s  %s", plotfile, datestr)) +
    #     theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
    #     theme(plot.tag.position = c(1, 0.01)) +
    #     theme(plot.tag = element_text(size = 6, hjust = 1))

    # ggsave(file = plotfile, plot = gp, width = 6, height = 4)

    print(variable)
    print(d2[, variable])
    kwt = kruskal.test(d2[, variable] ~ age_category, data = d2)
    print(kwt)
    pwwt = dunnTest(d2[, variable] ~ age_category, data=d2,
                 method = "bonf")
    print(pwwt)

    return # all done.
}

analysis_date <- sprintf("%s", format(Sys.time(), "_%d-%b-%Y"))
# specify the csv files, analyze the variables, and plot with y scale settings

fn <- "abr_data.csv"
# # # do the same analysis on different measures
do_stats(fn, "amplitude", 0, 12, analysis_date = analysis_date)
do_stats(fn, "threshold", 0, 100, analysis_date = analysis_date)
