# ABR Parameter file for tone pips
# 
[protocol]
protocol = 'tonepip'
stimulustype = 'tonepip'

[stimuli]
stim_dur = 1.2  # waveform duration
pip_duration  = 5e-3
pip_risefall = 5e-4
delay = [3e-3]
nreps = 500
stimulus_period = 1
npips = 30
interval = 25e-3
alternate=true
default_frequency = 4000.0
default_spl = 80.0
freqlist = [2000.0, 4000.0, 8000.0, 12000.0, 
            16000.0, 20000.0, 24000.0, 32000.0,
            48000.0]
dblist = [0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0]
[recording]
record_dur = 8e-3
LPF = 3000.0

